pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage("Build") {
            steps {
                sh 'mvn clean package'
            }
        }

        stage("SonarQube") {
            steps {
                script {
                    withSonarQubeEnv('servercyber') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }
        stage("deploy & OWASP Dependency-Check") {
    agent any
    steps {
        dependencyCheck additionalArguments: '''
            -o ./
            -s ./
            -f 'ALL'
            --prettyPrint''',
            odcInstallation: 'owasp-dependency',
            dependencyCheckPublisher pattern: 'dependency-check-report.xml'
    }
}

    }
}
